<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Optimal Project Prioritization Protocol • optimalppp</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Optimal Project Prioritization Protocol">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">optimalppp</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.0.4</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/optimalppp.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/prioritizr/optimalppp">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Optimal Project Prioritization Protocol</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/prioritizr/optimalppp/blob/master/vignettes/optimalppp.Rmd"><code>vignettes/optimalppp.Rmd</code></a></small>
      <div class="hidden name"><code>optimalppp.Rmd</code></div>

    </div>

    
    
<div id="overview" class="section level2">
<h2 class="hasAnchor">
<a href="#overview" class="anchor"></a>Overview</h2>
<p>The <em>optimalppp R</em> package provides methods for prioritizing funding of conservation projects using the ‘Protect Prioritization Protocol’. Projects can be prioritized by maximizing expected species richness or expected phylogenetic diversity. Prioritizations can be generated using a range of methods, such as exact algorithms which can identify optimal solutions, heuristic algorithms which have conventionally been used to identify solutions, and by randomly funding actions. This package also provides the functionality to visualize how well solutions maintain biodiversity.</p>
</div>
<div id="tutorial" class="section level2">
<h2 class="hasAnchor">
<a href="#tutorial" class="anchor"></a>Tutorial</h2>
<p>Here we will provide a short example showing how the <em>optimalppp R</em> package can be used to prioritize funding for conservation projects. With limited resources available for conservation <span class="citation">(Balmford <em>et al.</em> 2003)</span>, it is imperative that funds are prioritized for conservation projects which will create the best outcome. This realization led to development of the ‘Project Prioritization Protocol’ <span class="citation">(Joseph <em>et al.</em> 2009)</span>. This protocol, broadly speaking, involves evaluating conservation projects according to (i) the probability that they are expected to succeed, (ii) the probability that species will persist if their projects are funded and successful, and (iii) a metric describing the value of the conserved species <span class="citation">(evaluated in Bennett <em>et al.</em> 2014)</span>. Since its inception, project prioritization has diverged into ‘species prioritization’ <span class="citation">(e.g. Bennett <em>et al.</em> 2014)</span>, where each conservation project corresponds to a different species, and ‘priority threat management prioritization’ <span class="citation">(Chadés <em>et al.</em> 2015)</span>, where each conservation project pertains to a different threat which can affect multiple species. Here we do not differentiate between these types of problems—the <em>optimalppp R</em> package solves a general mathematical formulation that can handle both classes of problems.</p>
<p>The <em>optimalppp R</em> package provides two metrics for prioritizing and evaluating conservation projects. Firstly, prioritizations can be generated by maximizing ‘expected weighted species richness’. This metric is simply the sum of the species’ probabilities of persistence multiplied by their weights <span class="citation">(e.g. based on cultural importance or evolutionary significance; e.g. Faith 1992; Gerber <em>et al.</em> 2018)</span>. Secondly, prioritizations can be generated by maximizing ‘expected phylogenetic diversity’ <span class="citation">(Faith 1992, 2008)</span>. This metric uses phylogenetic data to quantify the amount of evolutionary history that is expected to persist into the future. Based on these metrics, prioritizations can be generated under a fixed budget by using exact algorithms (via the <a href="http://gurobi.com/">Gurobi optimization suite</a>), heuristic algorithms <span class="citation">(similar to Bennett <em>et al.</em> 2014)</span>, and random processes.</p>
<div id="data-simulation" class="section level3">
<h3 class="hasAnchor">
<a href="#data-simulation" class="anchor"></a>Data simulation</h3>
<p>To start off, we will set the seed for the random number generator to ensure reproducibility, load the <em>optimalppp R</em> package, and load the <em>ggtree R</em> package to plot phylogenetic trees. Please note that you will need install the <em>ggtree R</em> package from Bioconductor since it is not available on <a href="https://cran.r-project.org/">The Comprehensive R Archive Network (CRAN)</a>. This can be achieved with the following command <code><a href="https://www.rdocumentation.org/packages/base/topics/source">source("https://bioconductor.org/biocLite.R");biocLite("ggtree")</a></code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Random">set.seed</a></span>(<span class="dv">700</span>)
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(optimalppp)
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(ggtree)</code></pre></div>
<p>Now we will simulate a data set. This data set will contain conservation projects and conservation actions for 50 species. It will also contain species weight data. And also phylogenetic data that describe the evolutionary relationships between them. To learn more about what these parameters mean, check out <code><a href="../reference/ppp_simulate_data.html">?ppp_simulate_data</a></code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set simulation parameters</span>
number_species &lt;-<span class="st"> </span><span class="dv">50</span>
cost_mean &lt;-<span class="st"> </span><span class="dv">100</span>
cost_sd &lt;-<span class="st"> </span><span class="dv">5</span>
success_min_probability &lt;-<span class="st"> </span><span class="fl">0.7</span>
success_max_probability &lt;-<span class="st"> </span><span class="fl">0.99</span>
funded_min_persistence_probability &lt;-<span class="st"> </span><span class="fl">0.5</span>
funded_max_persistence_probability &lt;-<span class="st"> </span><span class="fl">0.9</span>
not_funded_min_persistence_probability &lt;-<span class="st"> </span><span class="fl">0.01</span>
not_funded_max_persistence_probability &lt;-<span class="st"> </span><span class="fl">0.4</span>
locked_in_proportion &lt;-<span class="st"> </span><span class="fl">0.1</span>
locked_out_proportion &lt;-<span class="st"> </span><span class="fl">0.1</span>

<span class="co"># simulate data</span>
sim &lt;-<span class="st"> </span><span class="kw"><a href="../reference/ppp_simulate_data.html">ppp_simulate_data</a></span>(number_species,
                         cost_mean,
                         cost_sd,
                         success_min_probability,
                         success_max_probability,
                         funded_min_persistence_probability,
                         funded_max_persistence_probability,
                         not_funded_min_persistence_probability,
                         not_funded_max_persistence_probability,
                         locked_in_proportion,
                         locked_out_proportion)

<span class="co"># extract the data</span>
project_data &lt;-<span class="st"> </span>sim<span class="op">$</span>project_data
action_data &lt;-<span class="st"> </span>sim<span class="op">$</span>action_data
species_data &lt;-<span class="st"> </span>sim<span class="op">$</span>species_data
tree &lt;-<span class="st"> </span>sim<span class="op">$</span>tree</code></pre></div>
<p>Now let’s examine the simulated data. Let’s look at the <code>action_data</code> object. This object stores information about various conservation actions in a tabular format (i.e. <code>tibble</code>). Each row corresponds to a different action, and each column describes different properties associated with the actions. These actions correspond to specific management actions that have known costs. For example, they may relate to baiting or trapping sites of conservation importance. In this table, the <code>"name"</code> column contains the name of each action, and the <code>"cost"</code> action denotes the cost of funding each project. It also contains additional columns for customizing the solutions, but we will ignore them for now. Note that the last project—the <code>"baseline_action"</code>—has a zero cost and is used subsequently to represent the baseline probability for species when no conservation actions are funded for them.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># preview first six rows of the table</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.data.frame">as.data.frame</a></span>(action_data))</code></pre></div>
<pre><code>##        name      cost locked_in locked_out
## 1 S1_action  99.56090     FALSE      FALSE
## 2 S2_action  98.85517     FALSE       TRUE
## 3 S3_action  99.57851     FALSE      FALSE
## 4 S4_action  91.29526      TRUE      FALSE
## 5 S5_action 105.06716     FALSE      FALSE
## 6 S6_action  98.91054     FALSE      FALSE</code></pre>
<p>Next, let’s examine the <code>project_data</code> object. This object stores information about various conservation projects in a tabular format (i.e. <code>tibble</code>). Each row corresponds to a different project, and each column describes various properties associated with the projects. Each project is associated with a single or multiple conservation actions (in the <code>action_data</code> object). For example, a conservation project may pertain to a set of conservation actions that relate to a single species or single geographic locality. In this table, the <code>"name"</code> column contains the name of each project, the <code>"success"</code> column denotes the probability of each project succeeding if it is funded, the <code>"S1"</code>–<code>"SN"</code> columns show the enhanced probability of each species persisting if the project is funded (where zeros mean that a species does not benefit from a project), and the <code>"S1_action"</code>–<code>"SN_action"</code> columns indicate which actions are associated with which projects. Note that the last project—the <code>"baseline_project"</code>—is associated with the <code>"baseline_action"</code> action. This project has a zero cost and represents the baseline probability of each species persisting if no other project is funded. Finally, although most projects in this example directly relate to a single species, you can input projects that directly affect the persistence of multiple species—you simply need to adjust the species persistence probabilities in the table. This format means that the <em>optimalppp R</em> package can be used to solve problems that are classically considered ‘species prioritization’ or ‘priority threat management’ problems.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># preview first six rows of the table</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.data.frame">as.data.frame</a></span>(project_data))</code></pre></div>
<pre><code>##         name   success        S1       S10       S11       S12       S13
## 1 S1_project 0.8616642 0.6199881 0.0000000 0.0000000 0.0000000 0.0000000
## 2 S2_project 0.8160988 0.0000000 0.6209851 0.0000000 0.0000000 0.0000000
## 3 S3_project 0.7018839 0.0000000 0.0000000 0.7495242 0.0000000 0.0000000
## 4 S4_project 0.7427809 0.0000000 0.0000000 0.0000000 0.5287815 0.0000000
## 5 S5_project 0.8139378 0.0000000 0.0000000 0.0000000 0.0000000 0.6540845
## 6 S6_project 0.9800510 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
##         S14 S15 S16 S17 S18 S19 S2 S20 S21 S22 S23 S24 S25 S26 S27 S28 S29
## 1 0.0000000   0   0   0   0   0  0   0   0   0   0   0   0   0   0   0   0
## 2 0.0000000   0   0   0   0   0  0   0   0   0   0   0   0   0   0   0   0
## 3 0.0000000   0   0   0   0   0  0   0   0   0   0   0   0   0   0   0   0
## 4 0.0000000   0   0   0   0   0  0   0   0   0   0   0   0   0   0   0   0
## 5 0.0000000   0   0   0   0   0  0   0   0   0   0   0   0   0   0   0   0
## 6 0.7916949   0   0   0   0   0  0   0   0   0   0   0   0   0   0   0   0
##   S3 S30 S31 S32 S33 S34 S35 S36 S37 S38 S39 S4 S40 S41 S42 S43 S44 S45
## 1  0   0   0   0   0   0   0   0   0   0   0  0   0   0   0   0   0   0
## 2  0   0   0   0   0   0   0   0   0   0   0  0   0   0   0   0   0   0
## 3  0   0   0   0   0   0   0   0   0   0   0  0   0   0   0   0   0   0
## 4  0   0   0   0   0   0   0   0   0   0   0  0   0   0   0   0   0   0
## 5  0   0   0   0   0   0   0   0   0   0   0  0   0   0   0   0   0   0
## 6  0   0   0   0   0   0   0   0   0   0   0  0   0   0   0   0   0   0
##   S46 S47 S48 S49 S5 S50 S6 S7 S8 S9 S1_action S2_action S3_action
## 1   0   0   0   0  0   0  0  0  0  0      TRUE     FALSE     FALSE
## 2   0   0   0   0  0   0  0  0  0  0     FALSE      TRUE     FALSE
## 3   0   0   0   0  0   0  0  0  0  0     FALSE     FALSE      TRUE
## 4   0   0   0   0  0   0  0  0  0  0     FALSE     FALSE     FALSE
## 5   0   0   0   0  0   0  0  0  0  0     FALSE     FALSE     FALSE
## 6   0   0   0   0  0   0  0  0  0  0     FALSE     FALSE     FALSE
##   S4_action S5_action S6_action S7_action S8_action S9_action S10_action
## 1     FALSE     FALSE     FALSE     FALSE     FALSE     FALSE      FALSE
## 2     FALSE     FALSE     FALSE     FALSE     FALSE     FALSE      FALSE
## 3     FALSE     FALSE     FALSE     FALSE     FALSE     FALSE      FALSE
## 4      TRUE     FALSE     FALSE     FALSE     FALSE     FALSE      FALSE
## 5     FALSE      TRUE     FALSE     FALSE     FALSE     FALSE      FALSE
## 6     FALSE     FALSE      TRUE     FALSE     FALSE     FALSE      FALSE
##   S11_action S12_action S13_action S14_action S15_action S16_action
## 1      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 2      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 3      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 4      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 5      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 6      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
##   S17_action S18_action S19_action S20_action S21_action S22_action
## 1      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 2      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 3      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 4      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 5      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 6      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
##   S23_action S24_action S25_action S26_action S27_action S28_action
## 1      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 2      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 3      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 4      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 5      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 6      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
##   S29_action S30_action S31_action S32_action S33_action S34_action
## 1      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 2      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 3      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 4      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 5      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 6      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
##   S35_action S36_action S37_action S38_action S39_action S40_action
## 1      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 2      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 3      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 4      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 5      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 6      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
##   S41_action S42_action S43_action S44_action S45_action S46_action
## 1      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 2      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 3      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 4      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 5      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
## 6      FALSE      FALSE      FALSE      FALSE      FALSE      FALSE
##   S47_action S48_action S49_action S50_action baseline_action
## 1      FALSE      FALSE      FALSE      FALSE           FALSE
## 2      FALSE      FALSE      FALSE      FALSE           FALSE
## 3      FALSE      FALSE      FALSE      FALSE           FALSE
## 4      FALSE      FALSE      FALSE      FALSE           FALSE
## 5      FALSE      FALSE      FALSE      FALSE           FALSE
## 6      FALSE      FALSE      FALSE      FALSE           FALSE</code></pre>
<p>Next up, let’s look at the <code>species_data</code> object. This object stores information about each species in tabular format. Here, each row corresponds to a different species and each column contains information about the species. It contains a <code>"name"</code> column which denotes the name of each species. Note that these names also appear as column names in the <code>project_data</code> object. It also contains a <code>"weight"</code> column that denotes the relative importance of each species. These weights reflect the evolutionary significance of each species, though they could also reflect cultural or economic importance too. You would simply need to adjust the values accordingly.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># preview first six rows of the table</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.data.frame">as.data.frame</a></span>(species_data))</code></pre></div>
<pre><code>##   name       weight
## 1  S25 0.0395923212
## 2   S9 0.0002666836
## 3  S11 0.0002666836
## 4  S12 0.0771402026
## 5  S34 0.0691797469
## 6   S6 0.0318333994</code></pre>
<p>Finally, let’s look at the <code>tree</code> object. This object stores information about the evolutionary relationships between the simulated species. If you want to read in your own phylogenetic data, check out the <a href="https://www.rdocumentation.org/packages/ape/versions/5.2/topics/read.nexus"><code>read.nexus</code> function from the <em>ape R</em> package</a>. Using this object, we can make a plot—specifically, a phylogram—depicting the evolutionary history of our simulated species.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot tree</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/ggtree/topics/ggtree">ggtree</a></span>(tree) <span class="op">+</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/ggtree/topics/geom_tiplab">geom_tiplab</a></span>(<span class="dt">size =</span> <span class="fl">2.5</span>)</code></pre></div>
<p><img src="optimalppp_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;"></p>
<div id="maximizing-expected-weighted-species-richness" class="section level4">
<h4 class="hasAnchor">
<a href="#maximizing-expected-weighted-species-richness" class="anchor"></a>Maximizing expected weighted species richness</h4>
<p>Now let’s generate some prioritizations using the simulated data. Specifically, we will generate prioritizations using the ‘expected weighted species richness’ metric. This metric is calculated by multiplying the probability that each species is expected to persist by the species’ weight value and summing these values together. It is often used in situations where phylogenetic data are not available. Let us assume that our resources are limited such that we can only spend, at most, $500 on funding conservation projects. In other words, our budget is capped at $500. Now, given the project data (<code>project_data</code>), the action data (<code>action_data</code>), the species data (<code>species_data</code>), and this budget (<code>500</code>), we can begin prioritizing funding for the conservation projects. Conventionally, conservation projects have been prioritized using heuristic algorithms <span class="citation">(e.g. Bennett <em>et al.</em> 2014)</span>, so let’s generate our first prioritization using these algorithms.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># prioritize funding using heuristic algorithm</span>
s1 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/ppp_heuristic_spp_solution.html">ppp_heuristic_spp_solution</a></span>(<span class="dt">x =</span> project_data, <span class="dt">y =</span> action_data,
                                 <span class="dt">spp =</span>  species_data, <span class="dt">budget =</span> <span class="dv">500</span>,
                                 <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                                 <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                                 <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                                 <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                                 <span class="dt">species_column_name =</span> <span class="st">"name"</span>,
                                 <span class="dt">weight_column_name =</span> <span class="st">"weight"</span>)

<span class="co"># print solution</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(s1)</code></pre></div>
<pre><code>## # A tibble: 1 x 57
##   solution method   obj budget  cost optimal S1_action S2_action S3_action
##      &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;   &lt;lgl&gt;     &lt;lgl&gt;     &lt;lgl&gt;    
## 1        1 heuri… 0.591    500  409. NA      FALSE     FALSE     FALSE    
## # ... with 48 more variables: S4_action &lt;lgl&gt;, S5_action &lt;lgl&gt;,
## #   S6_action &lt;lgl&gt;, S7_action &lt;lgl&gt;, S8_action &lt;lgl&gt;, S9_action &lt;lgl&gt;,
## #   S10_action &lt;lgl&gt;, S11_action &lt;lgl&gt;, S12_action &lt;lgl&gt;,
## #   S13_action &lt;lgl&gt;, S14_action &lt;lgl&gt;, S15_action &lt;lgl&gt;,
## #   S16_action &lt;lgl&gt;, S17_action &lt;lgl&gt;, S18_action &lt;lgl&gt;,
## #   S19_action &lt;lgl&gt;, S20_action &lt;lgl&gt;, S21_action &lt;lgl&gt;,
## #   S22_action &lt;lgl&gt;, S23_action &lt;lgl&gt;, S24_action &lt;lgl&gt;,
## #   S25_action &lt;lgl&gt;, S26_action &lt;lgl&gt;, S27_action &lt;lgl&gt;,
## #   S28_action &lt;lgl&gt;, S29_action &lt;lgl&gt;, S30_action &lt;lgl&gt;,
## #   S31_action &lt;lgl&gt;, S32_action &lt;lgl&gt;, S33_action &lt;lgl&gt;,
## #   S34_action &lt;lgl&gt;, S35_action &lt;lgl&gt;, S36_action &lt;lgl&gt;,
## #   S37_action &lt;lgl&gt;, S38_action &lt;lgl&gt;, S39_action &lt;lgl&gt;,
## #   S40_action &lt;lgl&gt;, S41_action &lt;lgl&gt;, S42_action &lt;lgl&gt;,
## #   S43_action &lt;lgl&gt;, S44_action &lt;lgl&gt;, S45_action &lt;lgl&gt;,
## #   S46_action &lt;lgl&gt;, S47_action &lt;lgl&gt;, S48_action &lt;lgl&gt;,
## #   S49_action &lt;lgl&gt;, S50_action &lt;lgl&gt;, baseline_action &lt;lgl&gt;</code></pre>
<p>The object <code>s1</code> contains the solution and also various statistics associated with the solution in a tabular format (i.e. <code>tibble</code>). Here, each row corresponds to a different solution. Specifically, the <code>"solution"</code> column contains an identifier for each solution (this is useful for methods that output multiple solutions), the <code>"obj"</code> column contains the objective value (i.e. the expected weighted species richness), the <code>"budget"</code> column stores the budget used for generating the solution, the <code>"cost"</code> column stores the cost of the solution, the <code>"optimal"</code> column indicates if the solution is known to be optimal (<code>NA</code> values mean the optimality is unknown), and the <code>"method"</code> column contains the name of the method used to generate the solution. The remaining columns (<code>"S1_project"</code>, <code>"S2_project"</code>, <code>"S3_project"</code>, …, <code>"S50_project"</code>, and <code>"baseline_project"</code>) indicate if a given project was prioritized for funding (<code>TRUE</code>) or not (<code>FALSE</code>).</p>
<p>To help interpret this solution, let’s make a plot. In this plot, each line corresponds to a different species. The length of each line represents the species’ weight, and the color of each line indicates the probability that each species is expected to persist. Asterisk symbols indicate which species benefit from funded projects which have all of their actions funded.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># visualize solution</span>
<span class="kw"><a href="../reference/ppp_plot_spp_solution.html">ppp_plot_spp_solution</a></span>(project_data, action_data, species_data, s1,
                      <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                      <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                      <span class="dt">species_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">weight_column_name =</span> <span class="st">"weight"</span>,
                      <span class="dt">symbol_hjust =</span> <span class="fl">0.01</span>)</code></pre></div>
<p><img src="optimalppp_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;"></p>
<p>In some cases, we might have projects for iconic species that are socially and economically important. To ensure that actions for these species are funded—regardless of cost-efficiency or benefit—we can “lock in” certain projects into the solution (conversely, we can also “lock out” certain actions if desired too). Although we could simply increase the weighting for such species, “locking in” such species provides a more transparent approach. Let us imagine that it is absolutely critical that the action for species S1 (named <code>"S1_action"</code>) receives funding. Let’s generate a solution using the heuristic algorithm with this constraint.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set locked in column to only lock in species S1</span>
action_data<span class="op">$</span>locked_in &lt;-<span class="st"> </span>action_data<span class="op">$</span>name <span class="op">==</span><span class="st"> "S1_action"</span>

<span class="co"># prioritize funding using heuristic algorithm</span>
s2 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/ppp_heuristic_spp_solution.html">ppp_heuristic_spp_solution</a></span>(<span class="dt">x =</span> project_data, <span class="dt">y =</span> action_data,
                                 <span class="dt">spp =</span> species_data, <span class="dt">budget =</span> <span class="dv">500</span>,
                                 <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                                 <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                                 <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                                 <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                                 <span class="dt">species_column_name =</span> <span class="st">"name"</span>,
                                 <span class="dt">weight_column_name =</span> <span class="st">"weight"</span>,
                                 <span class="dt">locked_in_column_name =</span> <span class="st">"locked_in"</span>)

<span class="co"># print solution</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(s2)</code></pre></div>
<pre><code>## # A tibble: 1 x 57
##   solution method   obj budget  cost optimal S1_action S2_action S3_action
##      &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;   &lt;lgl&gt;     &lt;lgl&gt;     &lt;lgl&gt;    
## 1        1 heuri… 0.585    500  407. NA      TRUE      FALSE     FALSE    
## # ... with 48 more variables: S4_action &lt;lgl&gt;, S5_action &lt;lgl&gt;,
## #   S6_action &lt;lgl&gt;, S7_action &lt;lgl&gt;, S8_action &lt;lgl&gt;, S9_action &lt;lgl&gt;,
## #   S10_action &lt;lgl&gt;, S11_action &lt;lgl&gt;, S12_action &lt;lgl&gt;,
## #   S13_action &lt;lgl&gt;, S14_action &lt;lgl&gt;, S15_action &lt;lgl&gt;,
## #   S16_action &lt;lgl&gt;, S17_action &lt;lgl&gt;, S18_action &lt;lgl&gt;,
## #   S19_action &lt;lgl&gt;, S20_action &lt;lgl&gt;, S21_action &lt;lgl&gt;,
## #   S22_action &lt;lgl&gt;, S23_action &lt;lgl&gt;, S24_action &lt;lgl&gt;,
## #   S25_action &lt;lgl&gt;, S26_action &lt;lgl&gt;, S27_action &lt;lgl&gt;,
## #   S28_action &lt;lgl&gt;, S29_action &lt;lgl&gt;, S30_action &lt;lgl&gt;,
## #   S31_action &lt;lgl&gt;, S32_action &lt;lgl&gt;, S33_action &lt;lgl&gt;,
## #   S34_action &lt;lgl&gt;, S35_action &lt;lgl&gt;, S36_action &lt;lgl&gt;,
## #   S37_action &lt;lgl&gt;, S38_action &lt;lgl&gt;, S39_action &lt;lgl&gt;,
## #   S40_action &lt;lgl&gt;, S41_action &lt;lgl&gt;, S42_action &lt;lgl&gt;,
## #   S43_action &lt;lgl&gt;, S44_action &lt;lgl&gt;, S45_action &lt;lgl&gt;,
## #   S46_action &lt;lgl&gt;, S47_action &lt;lgl&gt;, S48_action &lt;lgl&gt;,
## #   S49_action &lt;lgl&gt;, S50_action &lt;lgl&gt;, baseline_action &lt;lgl&gt;</code></pre>
<p>Let’s visualize this new solution with species S1 locked in.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># visualize solution</span>
<span class="kw"><a href="../reference/ppp_plot_spp_solution.html">ppp_plot_spp_solution</a></span>(project_data, action_data, species_data, s2,
                      <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                      <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                      <span class="dt">species_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">weight_column_name =</span> <span class="st">"weight"</span>,
                      <span class="dt">symbol_hjust =</span> <span class="fl">0.01</span>)</code></pre></div>
<p><img src="optimalppp_files/figure-html/unnamed-chunk-12-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Next, we might want to evaluate how well this solution compares to funding conservation actions at random. To achieve this, we need to generate solutions that contain randomly selected actions that (i) always include the baseline scenario project, and (ii) meet the budget. Fortunately, the <code>ppp_random_spp_solution</code> function does this for us. So, let’s generate 1,000 random solutions with a budget of $500.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># prioritize funding using random processes</span>
s3 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/ppp_random_spp_solution.html">ppp_random_spp_solution</a></span>(<span class="dt">x =</span> project_data, <span class="dt">y =</span> action_data,
                              <span class="dt">spp =</span> species_data, <span class="dt">budget =</span> <span class="dv">500</span>,
                              <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                              <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                              <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                              <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                              <span class="dt">species_column_name =</span> <span class="st">"name"</span>,
                              <span class="dt">weight_column_name =</span> <span class="st">"weight"</span>,
                              <span class="dt">locked_in_column_name =</span> <span class="st">"locked_in"</span>,
                              <span class="dt">number_solutions =</span> <span class="dv">1000</span>)

<span class="co"># print solution</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(s3)</code></pre></div>
<pre><code>## # A tibble: 1,000 x 57
##    solution method   obj budget  cost optimal S1_action S2_action S3_action
##       &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;   &lt;lgl&gt;     &lt;lgl&gt;     &lt;lgl&gt;    
##  1        1 random 0.497    500  408. NA      TRUE      FALSE     FALSE    
##  2        2 random 0.485    500  489. NA      TRUE      FALSE     FALSE    
##  3        3 random 0.461    500  414. NA      TRUE      FALSE     FALSE    
##  4        4 random 0.442    500  401. NA      TRUE      FALSE     FALSE    
##  5        5 random 0.501    500  491. NA      TRUE      FALSE     FALSE    
##  6        6 random 0.551    500  499. NA      TRUE      FALSE     FALSE    
##  7        7 random 0.457    500  494. NA      TRUE      FALSE     FALSE    
##  8        8 random 0.450    500  497. NA      TRUE      FALSE     FALSE    
##  9        9 random 0.453    500  497. NA      TRUE      TRUE      FALSE    
## 10       10 random 0.439    500  401. NA      TRUE      FALSE     FALSE    
## # ... with 990 more rows, and 48 more variables: S4_action &lt;lgl&gt;,
## #   S5_action &lt;lgl&gt;, S6_action &lt;lgl&gt;, S7_action &lt;lgl&gt;, S8_action &lt;lgl&gt;,
## #   S9_action &lt;lgl&gt;, S10_action &lt;lgl&gt;, S11_action &lt;lgl&gt;, S12_action &lt;lgl&gt;,
## #   S13_action &lt;lgl&gt;, S14_action &lt;lgl&gt;, S15_action &lt;lgl&gt;,
## #   S16_action &lt;lgl&gt;, S17_action &lt;lgl&gt;, S18_action &lt;lgl&gt;,
## #   S19_action &lt;lgl&gt;, S20_action &lt;lgl&gt;, S21_action &lt;lgl&gt;,
## #   S22_action &lt;lgl&gt;, S23_action &lt;lgl&gt;, S24_action &lt;lgl&gt;,
## #   S25_action &lt;lgl&gt;, S26_action &lt;lgl&gt;, S27_action &lt;lgl&gt;,
## #   S28_action &lt;lgl&gt;, S29_action &lt;lgl&gt;, S30_action &lt;lgl&gt;,
## #   S31_action &lt;lgl&gt;, S32_action &lt;lgl&gt;, S33_action &lt;lgl&gt;,
## #   S34_action &lt;lgl&gt;, S35_action &lt;lgl&gt;, S36_action &lt;lgl&gt;,
## #   S37_action &lt;lgl&gt;, S38_action &lt;lgl&gt;, S39_action &lt;lgl&gt;,
## #   S40_action &lt;lgl&gt;, S41_action &lt;lgl&gt;, S42_action &lt;lgl&gt;,
## #   S43_action &lt;lgl&gt;, S44_action &lt;lgl&gt;, S45_action &lt;lgl&gt;,
## #   S46_action &lt;lgl&gt;, S47_action &lt;lgl&gt;, S48_action &lt;lgl&gt;,
## #   S49_action &lt;lgl&gt;, S50_action &lt;lgl&gt;, baseline_action &lt;lgl&gt;</code></pre>
<p>Let’s visualize the first solution in the set of 1,000 randomly generated solutions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># visualize solution</span>
<span class="kw"><a href="../reference/ppp_plot_spp_solution.html">ppp_plot_spp_solution</a></span>(project_data, action_data, species_data, s3,
                      <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                      <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                      <span class="dt">species_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">weight_column_name =</span> <span class="st">"weight"</span>,
                      <span class="dt">symbol_hjust =</span> <span class="fl">0.01</span>, <span class="dt">n =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="optimalppp_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;"></p>
<p>We can now calculate how much better the solution generated using the heuristic algorithm performs than randomly funding conservation actions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># calculate how much better solution performs than random</span>
(s2<span class="op">$</span>obj <span class="op">-</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/mean">mean</a></span>(s3<span class="op">$</span>obj)) <span class="op">/</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/mean">mean</a></span>(s3<span class="op">$</span>obj)</code></pre></div>
<pre><code>## [1] 0.2336022</code></pre>
<p>Since the heuristic algorithm performs better than random, you might be tempted to think that the heuristic algorithm is pretty good. But you would be wrong. This is because the heuristic algorithms provide no guarantees on solution quality relative to optimality. This is because objective value associated with a solution tells us how good the solution is, but it does not tell us how good the solution is compared to the best possible solution (i.e. optimality). Therefore we cannot possibly be confident that the solution is any good at all. Fortunately, we can use exact algorithms to find the optimal solution to this problem <span class="citation">(for discussion on exact algorithms in conservation, see Underhill 1994; Rodrigues &amp; Gaston 2002)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># prioritize funding using exact algorithm</span>
s4 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/ppp_exact_spp_solution.html">ppp_exact_spp_solution</a></span>(<span class="dt">x =</span> project_data, <span class="dt">y =</span> action_data,
                             <span class="dt">spp =</span> species_data, <span class="dt">budget =</span> <span class="dv">500</span>,
                             <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                             <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                             <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                             <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                             <span class="dt">species_column_name =</span> <span class="st">"name"</span>,
                             <span class="dt">weight_column_name =</span> <span class="st">"weight"</span>,
                             <span class="dt">locked_in_column_name =</span> <span class="st">"locked_in"</span>)

<span class="co"># print solution</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(s4)</code></pre></div>
<pre><code>## # A tibble: 1 x 57
##   solution method   obj budget  cost optimal S1_action S2_action S3_action
##      &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;   &lt;lgl&gt;     &lt;lgl&gt;     &lt;lgl&gt;    
## 1        1 exact  0.603    500  498. TRUE    TRUE      FALSE     FALSE    
## # ... with 48 more variables: S4_action &lt;lgl&gt;, S5_action &lt;lgl&gt;,
## #   S6_action &lt;lgl&gt;, S7_action &lt;lgl&gt;, S8_action &lt;lgl&gt;, S9_action &lt;lgl&gt;,
## #   S10_action &lt;lgl&gt;, S11_action &lt;lgl&gt;, S12_action &lt;lgl&gt;,
## #   S13_action &lt;lgl&gt;, S14_action &lt;lgl&gt;, S15_action &lt;lgl&gt;,
## #   S16_action &lt;lgl&gt;, S17_action &lt;lgl&gt;, S18_action &lt;lgl&gt;,
## #   S19_action &lt;lgl&gt;, S20_action &lt;lgl&gt;, S21_action &lt;lgl&gt;,
## #   S22_action &lt;lgl&gt;, S23_action &lt;lgl&gt;, S24_action &lt;lgl&gt;,
## #   S25_action &lt;lgl&gt;, S26_action &lt;lgl&gt;, S27_action &lt;lgl&gt;,
## #   S28_action &lt;lgl&gt;, S29_action &lt;lgl&gt;, S30_action &lt;lgl&gt;,
## #   S31_action &lt;lgl&gt;, S32_action &lt;lgl&gt;, S33_action &lt;lgl&gt;,
## #   S34_action &lt;lgl&gt;, S35_action &lt;lgl&gt;, S36_action &lt;lgl&gt;,
## #   S37_action &lt;lgl&gt;, S38_action &lt;lgl&gt;, S39_action &lt;lgl&gt;,
## #   S40_action &lt;lgl&gt;, S41_action &lt;lgl&gt;, S42_action &lt;lgl&gt;,
## #   S43_action &lt;lgl&gt;, S44_action &lt;lgl&gt;, S45_action &lt;lgl&gt;,
## #   S46_action &lt;lgl&gt;, S47_action &lt;lgl&gt;, S48_action &lt;lgl&gt;,
## #   S49_action &lt;lgl&gt;, S50_action &lt;lgl&gt;, baseline_action &lt;lgl&gt;</code></pre>
<p>Now let’s visualize the optimal solution.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># visualize solution</span>
<span class="kw"><a href="../reference/ppp_plot_spp_solution.html">ppp_plot_spp_solution</a></span>(project_data, action_data, species_data, s4,
                      <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                      <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                      <span class="dt">species_column_name =</span> <span class="st">"name"</span>,
                      <span class="dt">weight_column_name =</span> <span class="st">"weight"</span>,
                      <span class="dt">symbol_hjust =</span> <span class="fl">0.01</span>)</code></pre></div>
<p><img src="optimalppp_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Now that we have the optimal solution (objective value = 0.603), we can see that the solution generated by the heuristic algorithm (objective value = 0.585) was indeed suboptimal.</p>
</div>
</div>
<div id="expected-phylogenetic-diversity" class="section level3">
<h3 class="hasAnchor">
<a href="#expected-phylogenetic-diversity" class="anchor"></a>Expected phylogenetic diversity</h3>
<p>Now that we’ve tried prioritizing projects using the species weights, let’s try using the phylogentic data. We can achieve this using the <code>tree</code> object instead of the <code>species_data</code> object.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># prioritize funding using exact algorithm</span>
s5 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/ppp_exact_phylo_solution.html">ppp_exact_phylo_solution</a></span>(<span class="dt">x =</span> project_data, <span class="dt">y =</span> action_data,
                               <span class="dt">tree =</span> tree, <span class="dt">budget =</span> <span class="dv">500</span>,
                               <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                               <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                               <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                               <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                               <span class="dt">locked_in_column_name =</span> <span class="st">"locked_in"</span>)

<span class="co"># print solution</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(s5)</code></pre></div>
<pre><code>## # A tibble: 1 x 57
##   solution method   obj budget  cost optimal S1_action S2_action S3_action
##      &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;   &lt;lgl&gt;     &lt;lgl&gt;     &lt;lgl&gt;    
## 1        1 exact   12.0    500  485. TRUE    TRUE      FALSE     FALSE    
## # ... with 48 more variables: S4_action &lt;lgl&gt;, S5_action &lt;lgl&gt;,
## #   S6_action &lt;lgl&gt;, S7_action &lt;lgl&gt;, S8_action &lt;lgl&gt;, S9_action &lt;lgl&gt;,
## #   S10_action &lt;lgl&gt;, S11_action &lt;lgl&gt;, S12_action &lt;lgl&gt;,
## #   S13_action &lt;lgl&gt;, S14_action &lt;lgl&gt;, S15_action &lt;lgl&gt;,
## #   S16_action &lt;lgl&gt;, S17_action &lt;lgl&gt;, S18_action &lt;lgl&gt;,
## #   S19_action &lt;lgl&gt;, S20_action &lt;lgl&gt;, S21_action &lt;lgl&gt;,
## #   S22_action &lt;lgl&gt;, S23_action &lt;lgl&gt;, S24_action &lt;lgl&gt;,
## #   S25_action &lt;lgl&gt;, S26_action &lt;lgl&gt;, S27_action &lt;lgl&gt;,
## #   S28_action &lt;lgl&gt;, S29_action &lt;lgl&gt;, S30_action &lt;lgl&gt;,
## #   S31_action &lt;lgl&gt;, S32_action &lt;lgl&gt;, S33_action &lt;lgl&gt;,
## #   S34_action &lt;lgl&gt;, S35_action &lt;lgl&gt;, S36_action &lt;lgl&gt;,
## #   S37_action &lt;lgl&gt;, S38_action &lt;lgl&gt;, S39_action &lt;lgl&gt;,
## #   S40_action &lt;lgl&gt;, S41_action &lt;lgl&gt;, S42_action &lt;lgl&gt;,
## #   S43_action &lt;lgl&gt;, S44_action &lt;lgl&gt;, S45_action &lt;lgl&gt;,
## #   S46_action &lt;lgl&gt;, S47_action &lt;lgl&gt;, S48_action &lt;lgl&gt;,
## #   S49_action &lt;lgl&gt;, S50_action &lt;lgl&gt;, baseline_action &lt;lgl&gt;</code></pre>
<p>Now let’s visualize this optimal solution based on using phylogenetic data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># visualize solution</span>
<span class="kw"><a href="../reference/ppp_plot_phylo_solution.html">ppp_plot_phylo_solution</a></span>(project_data, action_data, tree, s5,
                        <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                        <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                        <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                        <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>,
                        <span class="dt">symbol_hjust =</span> <span class="fl">0.01</span>)</code></pre></div>
<p><img src="optimalppp_files/figure-html/unnamed-chunk-19-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Earlier, we generated a solution using species weights that reflected evolutionary importance (i.e. the <code>s4</code> object). Let’s compare the optimal solution based on phylogenetic data to the optimal solution based on species weights. To do this, we will use the solution in the <code>s4</code> object to manually specify a solution for the expected phylogenetic diversity problem.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># evaluate solution based on species weights</span>
s6 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/ppp_manual_phylo_solution.html">ppp_manual_phylo_solution</a></span>(<span class="dt">x =</span> project_data, <span class="dt">y =</span> action_data, <span class="dt">tree =</span> tree,
                                <span class="dt">solution =</span> s4[, action_data<span class="op">$</span>name],
                                <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                                <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                                <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                                <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>)

<span class="co"># print solution</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(s6)</code></pre></div>
<pre><code>## # A tibble: 1 x 57
##   solution method   obj budget  cost optimal S1_action S2_action S3_action
##      &lt;int&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;   &lt;lgl&gt;     &lt;lgl&gt;     &lt;lgl&gt;    
## 1        1 manual  11.6     NA  498. NA      TRUE      FALSE     FALSE    
## # ... with 48 more variables: S4_action &lt;lgl&gt;, S5_action &lt;lgl&gt;,
## #   S6_action &lt;lgl&gt;, S7_action &lt;lgl&gt;, S8_action &lt;lgl&gt;, S9_action &lt;lgl&gt;,
## #   S10_action &lt;lgl&gt;, S11_action &lt;lgl&gt;, S12_action &lt;lgl&gt;,
## #   S13_action &lt;lgl&gt;, S14_action &lt;lgl&gt;, S15_action &lt;lgl&gt;,
## #   S16_action &lt;lgl&gt;, S17_action &lt;lgl&gt;, S18_action &lt;lgl&gt;,
## #   S19_action &lt;lgl&gt;, S20_action &lt;lgl&gt;, S21_action &lt;lgl&gt;,
## #   S22_action &lt;lgl&gt;, S23_action &lt;lgl&gt;, S24_action &lt;lgl&gt;,
## #   S25_action &lt;lgl&gt;, S26_action &lt;lgl&gt;, S27_action &lt;lgl&gt;,
## #   S28_action &lt;lgl&gt;, S29_action &lt;lgl&gt;, S30_action &lt;lgl&gt;,
## #   S31_action &lt;lgl&gt;, S32_action &lt;lgl&gt;, S33_action &lt;lgl&gt;,
## #   S34_action &lt;lgl&gt;, S35_action &lt;lgl&gt;, S36_action &lt;lgl&gt;,
## #   S37_action &lt;lgl&gt;, S38_action &lt;lgl&gt;, S39_action &lt;lgl&gt;,
## #   S40_action &lt;lgl&gt;, S41_action &lt;lgl&gt;, S42_action &lt;lgl&gt;,
## #   S43_action &lt;lgl&gt;, S44_action &lt;lgl&gt;, S45_action &lt;lgl&gt;,
## #   S46_action &lt;lgl&gt;, S47_action &lt;lgl&gt;, S48_action &lt;lgl&gt;,
## #   S49_action &lt;lgl&gt;, S50_action &lt;lgl&gt;, baseline_action &lt;lgl&gt;</code></pre>
<p>We can see that the solution generated using species weights to account for evolutionary importance (objective value = 11.647) performed worse than the solution generated using phylogenetic data (objective value = 12.042) when evaluated using the phylogenetic data. This result is important because it suggests that conservation prioritizations may benefit by using better quality data.</p>
<p>Finally, let’s examine the trade-off between conservation expenditure and the amount of evolutionary history that is expected to persist. We can achieve this by creating a series of prioritizations using increasing budgets, and then plotting the objective values against the cost of the prioritizations. Here we will use fifty different budgets to reduce run time, though in practice you would use a much larger number (e.g. 10,000) to create a more accurate trade-off curve.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># create a vector of 50 different budgets</span>
budgets &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(action_data<span class="op">$</span>cost), <span class="dt">length.out =</span> <span class="dv">50</span>)

<span class="co"># create prioritizations using different budgets</span>
solution_data &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/do.call">do.call</a></span>(rbind, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">lapply</a></span>(budgets, ppp_exact_phylo_solution,
                                       <span class="dt">x =</span> project_data, <span class="dt">y =</span> action_data,
                                       <span class="dt">tree =</span> tree,
                                       <span class="dt">project_column_name =</span> <span class="st">"name"</span>,
                                       <span class="dt">success_column_name =</span> <span class="st">"success"</span>,
                                       <span class="dt">action_column_name =</span> <span class="st">"name"</span>,
                                       <span class="dt">cost_column_name =</span> <span class="st">"cost"</span>))

<span class="co"># create a data.frame to plot the results</span>
plot_data &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">cost =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(action_data<span class="op">$</span>cost), <span class="dt">length.out =</span> <span class="fl">1e+4</span>))
plot_data<span class="op">$</span>obj &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/approxfun">approx</a></span>(<span class="dt">x =</span> solution_data<span class="op">$</span>cost, <span class="dt">y =</span> solution_data<span class="op">$</span>obj,
                        <span class="dt">xout =</span> plot_data<span class="op">$</span>cost, <span class="dt">method =</span> <span class="st">"constant"</span>)<span class="op">$</span>y

<span class="co"># plot relationship between cost and conservation value</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(obj <span class="op">~</span><span class="st"> </span>cost, <span class="dt">data =</span> plot_data, <span class="dt">type =</span> <span class="st">"l"</span>, <span class="dt">xlab =</span> <span class="st">"Cost ($)"</span>,
     <span class="dt">ylab =</span> <span class="st">"Expected phylogenetic diversity (million years)"</span>)</code></pre></div>
<p><img src="optimalppp_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="citation" class="section level2">
<h2 class="hasAnchor">
<a href="#citation" class="anchor"></a>Citation</h2>
<p>Please use the following citation to cite the <em>optimalppp R</em> package in publications:</p>
<p>Hanson JO, Schuster R, Strimas-Mackey M, Bennett J, (2018). optimalppp: Optimal Project Prioritization Protocol. R package version 0.0.0.4. Available at <a href="https://github.com/prioritizr/optimalppp" class="uri">https://github.com/prioritizr/optimalppp</a>.</p>
</div>
<div id="references" class="section level2 unnumbered">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references">
<div id="ref-r2">
<p>Balmford, A., Gaston, K.J., Blyth, S., James, A. &amp; Kapos, V. (2003). Global variation in terrestrial conservation costs, conservation benefits, and unmet conservation needs. <em>Proceedings of the National Academy of Sciences</em>, <em>100</em>, 1046–1050.</p>
</div>
<div id="ref-r4">
<p>Bennett, J.R., Elliott, G., Mellish, B., Joseph, L.N., Tulloch, A.I., Probert, W.J., Di Fonzo, M.M., Monks, J.M., Possingham, H.P. &amp; Maloney, R. (2014). Balancing phylogenetic diversity and species numbers in conservation prioritizat, using a case study of threatened species in New Zealand. <em>Biological Conservation</em>, <em>174</em>, 47–54.</p>
</div>
<div id="ref-r5">
<p>Chadés, I., Nicol, S., Leeuwen, S. van, Walters, B., Firn, J., Reeson, A., Martin, T.G. &amp; Carwardine, J. (2015). Benefits of integrating complementarity into priority threat management. <em>Conservation Biology</em>, <em>29</em>, 525–536.</p>
</div>
<div id="ref-r9">
<p>Faith, D.P. (1992). Conservation evaluation and phylogenetic diversity. <em>Biological Conservation</em>, <em>61</em>, 1–10.</p>
</div>
<div id="ref-r8">
<p>Faith, D.P. (2008). Threatened species and the potential loss of phylogenetic diversity: Conservation scenarios based on estimated extinction probabilities and phylogenetic risk analysis. <em>Conservation Biology</em>, <em>22</em>, 1461–1470.</p>
</div>
<div id="ref-r11">
<p>Gerber, L.R., Runge, M.C., Maloney, R.F., Iacona, G.D., Drew, C.A., Avery-Gomm, S., Brazill-Boast, J., Crouse, D., Epanchin-Niell, R.S., Hall, S.B. &amp; others. (2018). Endangered species recovery: A resource allocation problem. <em>Science</em>, <em>362</em>, 284–286.</p>
</div>
<div id="ref-r3">
<p>Joseph, L.N., Maloney, R.F. &amp; Possingham, H.P. (2009). Optimal allocation of resources among threatened species: A project prioritization protocol. <em>Conservation Biology</em>, <em>23</em>, 328–338.</p>
</div>
<div id="ref-r13">
<p>Rodrigues, A.S. &amp; Gaston, K.J. (2002). Optimisation in reserve selection procedures—why not? <em>Biological Conservation</em>, <em>107</em>, 123–129.</p>
</div>
<div id="ref-r12">
<p>Underhill, L. (1994). Optimal and suboptimal reserve selection algorithms. <em>Biological Conservation</em>, <em>70</em>, 85–87.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#overview">Overview</a></li>
      <li><a href="#tutorial">Tutorial</a></li>
      <li><a href="#citation">Citation</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by <a href="https://jeffrey-hanson.com">Jeffrey O Hanson</a>, <a href="http://www.richard-schuster.com/">Richard Schuster</a>, <a href="http://strimas.com">Matthew Strimas-Mackey</a>, <a href="https://josephrbennett.wordpress.com/">Joeseph Bennett</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.2.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
