# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_branch_matrix <- function(x) {
    .Call(`_optimalppp_rcpp_branch_matrix`, x)
}

rcpp_miqp_formulation <- function(spp, budget, branch_matrix, branch_lengths, costs, success_probabilities, locked_in, locked_out) {
    .Call(`_optimalppp_rcpp_miqp_formulation`, spp, budget, branch_matrix, branch_lengths, costs, success_probabilities, locked_in, locked_out)
}

