# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_random_solution <- function(spp, actions, budget, branch_matrix, branch_lengths, costs, locked_in, locked_out, n_solutions) {
    .Call(`_optimalppp_rcpp_random_solution`, spp, actions, budget, branch_matrix, branch_lengths, costs, locked_in, locked_out, n_solutions)
}

rcpp_branch_matrix <- function(x) {
    .Call(`_optimalppp_rcpp_branch_matrix`, x)
}

rcpp_branch_probabilities <- function(spp, branch_matrix, solutions) {
    .Call(`_optimalppp_rcpp_branch_probabilities`, spp, branch_matrix, solutions)
}

rcpp_heuristic_phylo_solution <- function(spp, actions, budget, branch_matrix, branch_lengths, costs, locked_in, locked_out) {
    .Call(`_optimalppp_rcpp_heuristic_phylo_solution`, spp, actions, budget, branch_matrix, branch_lengths, costs, locked_in, locked_out)
}

rcpp_mip_formulation <- function(spp, actions, budget, branch_matrix, branch_lengths, costs, locked_in, locked_out, n_approx_points) {
    .Call(`_optimalppp_rcpp_mip_formulation`, spp, actions, budget, branch_matrix, branch_lengths, costs, locked_in, locked_out, n_approx_points)
}

rcpp_ppp_epd <- function(spp, actions, branch_matrix, branch_lengths, solutions) {
    .Call(`_optimalppp_rcpp_ppp_epd`, spp, actions, branch_matrix, branch_lengths, solutions)
}

